{"protocolVersion":"0.1.1","runnerVersion":null,"pid":65436,"type":"start","time":0}
{"suite":{"id":0,"platform":"vm","path":"/Users/sklose/IdeaProjects/flutter_sonarqube/test/widget_test.dart"},"type":"suite","time":0}
{"test":{"id":1,"name":"loading /Users/sklose/IdeaProjects/flutter_sonarqube/test/widget_test.dart","suiteID":0,"groupIDs":[],"metadata":{"skip":false,"skipReason":null},"line":null,"column":null,"url":null},"type":"testStart","time":1}
{"count":1,"type":"allSuites","time":13}

[{"event":"test.startedProcess","params":{"observatoryUri":null}}]
{"testID":1,"result":"success","skipped":false,"hidden":true,"type":"testDone","time":1879}
{"group":{"id":2,"suiteID":0,"parentID":null,"name":"","metadata":{"skip":false,"skipReason":null},"testCount":1,"line":null,"column":null,"url":null},"type":"group","time":1883}
{"test":{"id":3,"name":"Counter increments smoke test","suiteID":0,"groupIDs":[2],"metadata":{"skip":false,"skipReason":null},"line":138,"column":5,"url":"package:flutter_test/src/widget_tester.dart","root_line":14,"root_column":3,"root_url":"file:///Users/sklose/IdeaProjects/flutter_sonarqube/test/widget_test.dart"},"type":"testStart","time":1884}
{"testID":3,"messageType":"print","message":"══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════\nThe following TestFailure object was thrown running a test:\n  Expected: exactly one matching node in the widget tree\n  Actual: _TextFinder:<zero widgets with text \"1\" (ignoring offstage widgets)>\n   Which: means none were found but one was expected\n\nWhen the exception was thrown, this was the stack:\n#4      main.<anonymous closure> (file:///Users/sklose/IdeaProjects/flutter_sonarqube/test/widget_test.dart:28:5)\n<asynchronous suspension>\n<asynchronous suspension>\n(elided one frame from package:stack_trace)\n...\n\nThis was caught by the test expectation on the following line:\n  file:///Users/sklose/IdeaProjects/flutter_sonarqube/test/widget_test.dart line 28\nThe test description was:\n  Counter increments smoke test\n════════════════════════════════════════════════════════════════════════════════════════════════════","type":"print","time":2636}
{"testID":3,"error":"Test failed. See exception logs above.\nThe test description was: Counter increments smoke test","stackTrace":"","isFailure":false,"type":"error","time":2639}
{"testID":3,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":2640}
{"success":false,"type":"done","time":2670}
